### ISSUE TITLE
Security - Axios version

### ISSUE THREAD

**Issue by camc314** [jellyfin-archive/jellyfin-client-axios#9]
When running `npm audit`, it reports a high severity issue in the current version of axios.

Axios needs to be updated to a minimum version of 0.21.1 (The current version uses 0.19.2)

**Comment by ferferga** [comment]
Fixed on 4d0117f

**Comment by camc314** [comment]
@ferferga I'll leave this up to you as to whether to reopen this. But there is no new version on npm, so clients using the package will still be affected.

**Comment by ferferga** [comment]
@Camc314 I know, I'm waiting for @anthonylavado to provide the token to the repo secrets.

As long as that's done, CI will be working  and a new version (both for stable and unstable) will be published.

I'll pin this in the meantime.

**Comment by anthonylavado** [comment]
Token added. Try now?

**Comment by ferferga** [comment]
Version live now on npm.

Unpinning.
